name: Code Style

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Download php-cs-fixer
        run: |
          curl -L https://cs.symfony.com/download/php-cs-fixer-v2.phar -o php-cs-fixer 
          sudo chmod a+x php-cs-fixer
          sudo mv php-cs-fixer /usr/local/bin/php-cs-fixer

      - name: launch validation
        run: php-cs-fixer fix --dry-run src
