name: Hadolint
on: push

jobs:
  hadolint:
    name: Hadolint
    runs-on: ubuntu-latest
    container: docker://hadolint/hadolint:latest-debian
    steps:
      - uses: actions/checkout@v2
      - name: Launch Hadolint on the Dockerfile
        run: hadolint Dockerfile
