name: Hadolint
on: push

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Hadolint
        uses: actions/checkout@v2
      - name: install Docker
        run: curl -sSL https://get.docker.com | sh
      - name: run Hadolint
        run: docker run --rm -i hadolint/hadolint < Dockerfile
