name: Test unit and functional
on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install composer
        run: composer install
      - name: Launch test unit
        run: make test_unit
      - name: Launch test functional
        run: make test
